api-endpoints
learn-academy-2021-echo/cat-tinder-backend-persians-style-yann-raul pull request #2
Opened 2022-02-04 22:56 UTC by yannsf29

2022-02-04 23:07 UTC, WalkerTexas-coder requested changes
One change requested

2022-02-04 23:07 UTC, WalkerTexas-coder commented on app/controllers/cats_controller.rb
> +   end
Please clean up the white space and indentation.

2022-02-07 17:50 UTC, Echo5Mike commented
Cleaned up code.

2022-02-07 18:09 UTC, WalkerTexas-coder approved these changes
Okay let's keep it going.

2022-02-07 19:32 UTC, merged